# image will be published to ghcr.io/<user>/<name>
name: ublue
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: script
    scripts:
      - pins.sh

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/che/nerd-fonts/repo/fedora-%OS_VERSION%/che-nerd-fonts-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
    install:
      - qalculate-gtk
      - kitty
      - fira-code-fonts
      - fontawesome-fonts
      - fuzzel
      - grim
      - gnome-keyring
      - mako
      - mpv
      - mesa-vdpau-drivers-freeworld
      - nerd-fonts
      - pipewire-plugin-libcamera
      - polkit-gnome
      - powerline-fonts
      - slurp
      - solaar
      - swappy
      - squeekboard
      - wlsunset
      - wl-clipboard
      - wl-mirror
      - wev
      - wtype
      # (mine) utils:
      - bat
      - ddcutil
      - difftastic
      - dutree
      - erofs-utils
      - eza
      - fd-find
      - fish
      - fzf
      - gdb
      - git-delta
      - gparted
      - guestfs-tools
      - ncdu
      - perl
      - playerctl
      - policycoreutils
      - ranger
      - ripgrep
      - qemu-kvm
      - syncthing
      - udiskie
      - valgrind
      - zenity
      # (mine) external repos:
      - eww-wayland-git
      - aylurs-gtk-shell
      - tailscale
      - hypridle
      - hyprland
      - hyprland-contrib
      # - hyprland-plugins
      - hyprlock
      - hyprpicker
      - hyprshot
      - hyprpaper
      - starship
      - nwg-clipman
      - xdg-desktop-portal-hyprland
      - waybar-git
      # niri
      - niri
      # cosmic
      - cosmic-desktop
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - waybar

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      - xyz.armcord.ArmCord
      - io.github.celluloid_player.Celluloid
      - com.bitwarden.desktop
      - com.parsecgaming.parsec
      - com.slack.Slack
      - com.spotify.Client
      - com.sublimemerge.App
      - com.visualstudio.code-oss
      - fr.handbrake.ghb
      - md.obsidian.Obsidian
      - com.microsoft.Edge
      - org.telegram.desktop
      - org.videolan.VLC
      - app.drey.Warp
      - app.getclipboard.Clipboard
      - org.kde.dolphin
      - org.pipewire.Helvum
      - com.github.wwmm.easyeffects
      # - org.freedesktop.Platform.ffmpeg-full
      - com.github.KRTirtho.Spotube
      - io.github.nokse22.minitext
      - dev.serebit.Waycheck
      - org.mozilla.Thunderbird
      - org.gnome.Fractal
      - net.sapples.LiveCaptions
      - com.github.tenderowl.frog
      - com.github.jeromerobert.pdfarranger
      - org.gnome.Weather
      - com.github.qarmin.czkawka
      - com.parsecgaming.parsec
      - org.gnome.SimpleScan
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      remove:
      # - org.gnome.eog
      #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
